spring:
  profiles:
    active: qa

---

spring:
  config:
    activate:
      on-profile: qa
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    password: sqlrootpass
    url: jdbc:mysql://localhost:3306/Departments-qa
    username: root
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

management:
  endpoints:
    web:
      exposure:
        include: "*"

---

spring:
  config:
    activate:
      on-profile: prod
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    password: sqlrootpass
    url: jdbc:mysql://localhost:3306/Departments-prod
    username: root
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
